export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PWD = 'CHANGE_PWD';
export const CHANGE_AUTH_STATUS = 'CHANGE_AUTH_STATUS';
export const TOGGLE_VISIBILITY = "TOGGLE_VISIBILITY";
export const CHANGE_NEWS_COUNTRY = 'CHANGE_NEWS_COUNTRY';